### ISSUE TITLE
北邮镜像坏了？

### ISSUE THREAD

**Issue by firsttopman** [bupticybee/icyface_website#1]
外校的，原来一直是通过博主的http://bbs.cloud.icybee.cn/ 上的，从v2ex一直追到这哈。有没有其它方法？

**Comment by bupticybee** [comment]
我其实这几天知道坏了，不过这几天搬家，一直没时间修（真的一刻时间都木有），但是今天早上搬完啦，于是就修了已经，现在应该是已经ok了，至少我test都过了

**Comment by bupticybee** [comment]
ps：下次可以通过icybee@yeah.net联系我，写在issue里边怪怪的，我close了
